OS: 36 Best Practices
digitalpolygon/wp-starter-shayaan pull request #9
Opened 2024-07-08 15:03 UTC by shayaanmiyy

Jira Ticket URL: https://digitalpolygon.atlassian.net/browse/OS-36

## Exercises:

### Code Review:

- Review and refactor existing Twig templates for readability and maintainability.

- Apply best practices such as DRY (Don't Repeat Yourself) and KISS (Keep It Simple, Stupid).

### Template Caching:

- Implement caching strategies to optimize Twig template performance.

- Measure the performance improvements using tools like Query Monitor.

### Error Handling:

- Add error handling to Twig templates to gracefully handle missing data or other issues.

- Test your templates by simulating common errors and verifying the error handling works correctly.

![image](https://github.com/digitalpolygon/wp-starter-shayaan/assets/69762513/3689c7d9-0690-4f44-9576-286bbb6dfd95)

2024-07-10 16:33 UTC, niteshsyngenta11 requested changes
Added some comments.

2024-07-10 16:33 UTC, niteshsyngenta11 commented on web/app/themes/dp-timber-theme/views/partial/advance.twig
> +        {# Here I used DRY, Instead of creating New Input I used Atoms #}
Fix indenation issues.

2024-07-10 16:33 UTC, niteshsyngenta11 commented on web/app/themes/dp-timber-theme/views/partial/best-practices.twig
> +	{% endif %}
Fix indentation issues.

2024-07-10 16:33 UTC, niteshsyngenta11 commented on web/app/themes/dp-timber-theme/views/partial/best-practices.twig
> +	{% if user.role == 'admin' %}
Use === instead ==

2024-07-10 16:33 UTC, niteshsyngenta11 commented on web/app/themes/dp-timber-theme/views/partial/best-practices.twig
> +			{{ username }}</p>
This can go in a single line.

2024-07-10 16:50 UTC, shayaanmiyy commented on web/app/themes/dp-timber-theme/views/partial/advance.twig
> +        {# Here I used DRY, Instead of creating New Input I used Atoms #}
Yes, sure

2024-07-10 16:51 UTC, shayaanmiyy commented on web/app/themes/dp-timber-theme/views/partial/best-practices.twig
> +			{{ username }}</p>
Yes, I will do it

2024-07-10 16:51 UTC, shayaanmiyy commented on web/app/themes/dp-timber-theme/views/partial/best-practices.twig
> +	{% endif %}
Yes

2024-07-10 18:07 UTC, shayaanmiyy commented on web/app/themes/dp-timber-theme/views/partial/best-practices.twig
> +	{% if user.role == 'admin' %}
Yes, I fixed it

2024-07-11 10:15 UTC, niteshsyngenta11 approved these changes
Looks good 👍

2024-07-11 10:16 UTC, merged